# Generated by Django 5.2.17 on 2026-09-07 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome de identificação administrativa do projeto.', max_length=150, verbose_name='Nome do Projeto')),
                ('slug', models.SlugField(help_text='Identificador amigável de URL exclusivo do site.', max_length=100, unique=True, verbose_name='Endereço (Slug)')),
                ('tipo', models.CharField(choices=[('biosite', 'BioSite'), ('landing_page', 'Landing Page'), ('site', 'Site Institucional'), ('portfolio', 'Portfólio'), ('cardapio', 'Cardápio Digital'), ('outro', 'Outro')], db_index=True, default='biosite', max_length=30, verbose_name='Tipo de Projeto')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado'), ('suspenso', 'Suspenso')], db_index=True, default='rascunho', max_length=20, verbose_name='Status')),
                ('descricao_interna', models.TextField(blank=True, help_text='Notas administrativas internas sobre o escopo ou contrato.', verbose_name='Descrição Interna')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de visualização no workspace (opcional).', null=True, upload_to='projetos/thumbnails/', verbose_name='Miniatura')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
                ('cliente', models.ForeignKey(help_text='Cliente comercial proprietário deste projeto.', on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'projeto de site',
                'verbose_name_plural': 'projetos de sites',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
