# Generated by Django 5.2.17 on 2026-09-07 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ordem', models.PositiveIntegerField(default=10, verbose_name='Ordem')),
                ('tipo_layout', models.CharField(choices=[('stack', 'Pilha Vertical (Stack)'), ('row', 'Linha Horizontal (Row)'), ('grid', 'Grade (Grid)'), ('overlay', 'Sobreposição (Overlay)')], default='stack', max_length=30, verbose_name='Tipo de Layout')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('configuracao', models.JSONField(blank=True, default=dict, verbose_name='Configuração')),
                ('estilos', models.JSONField(blank=True, default=dict, verbose_name='Estilos')),
                ('parent', models.ForeignKey(blank=True, help_text='Container ancestral para layouts compostos (máx 3 níveis).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='sites.containersite', verbose_name='Container Pai')),
            ],
            options={
                'verbose_name': 'container do site',
                'verbose_name_plural': 'containers do site',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ElementoSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(db_index=True, max_length=50, verbose_name='Tipo de Elemento')),
                ('ordem', models.PositiveIntegerField(default=10, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('conteudo', models.JSONField(blank=True, default=dict, verbose_name='Conteúdo')),
                ('estilos', models.JSONField(blank=True, default=dict, help_text="Estilos mobile-first: {'base': {...}, 'desktop': {...}}.", verbose_name='Estilos')),
                ('configuracao', models.JSONField(blank=True, default=dict, verbose_name='Configuração')),
                ('versao_schema', models.PositiveIntegerField(default=1, verbose_name='Versão do Schema')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='sites.containersite', verbose_name='Container')),
            ],
            options={
                'verbose_name': 'elemento do site',
                'verbose_name_plural': 'elementos do site',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PaginaSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(help_text='Ex: Início, Sobre, Serviços, Contato.', max_length=150, verbose_name='Título da Página')),
                ('slug', models.SlugField(help_text='Identificador da página na URL (ex: inicio, sobre).', max_length=100, verbose_name='Slug da Página')),
                ('ordem', models.PositiveIntegerField(default=10, help_text='Ordem sequencial da página na navegação.', verbose_name='Ordem')),
                ('eh_inicial', models.BooleanField(default=False, help_text='Indica se esta é a página principal exibida na raiz do site.', verbose_name='Página Inicial')),
                ('ativa', models.BooleanField(default=True, help_text='Páginas inativas ficam ocultas na navegação pública.', verbose_name='Ativa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='sites.projetosite', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'página do site',
                'verbose_name_plural': 'páginas do site',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SecaoSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_interno', models.CharField(help_text='Identificador administrativo da seção (ex: Hero Principal, Contato).', max_length=150, verbose_name='Nome Interno')),
                ('ordem', models.PositiveIntegerField(default=10, help_text='Posição vertical da seção na página.', verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('altura_minima', 'Altura Mínima'), ('tela_cheia', 'Tela Cheia')], default='normal', max_length=30, verbose_name='Tipo de Seção')),
                ('ativa', models.BooleanField(default=True, help_text='Seções desativadas não são renderizadas publicamente.', verbose_name='Ativa')),
                ('configuracao', models.JSONField(blank=True, default=dict, verbose_name='Configuração')),
                ('estilos', models.JSONField(blank=True, default=dict, help_text="Estilos estruturais mobile-first: {'base': {...}, 'desktop': {...}}.", verbose_name='Estilos')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='sites.paginasite', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'seção do site',
                'verbose_name_plural': 'seções do site',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.AddField(
            model_name='containersite',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='sites.secaosite', verbose_name='Seção'),
        ),
        migrations.AddConstraint(
            model_name='paginasite',
            constraint=models.UniqueConstraint(fields=('projeto', 'slug'), name='unique_pagina_slug_por_projeto'),
        ),
        migrations.AddConstraint(
            model_name='paginasite',
            constraint=models.UniqueConstraint(condition=models.Q(('eh_inicial', True)), fields=('projeto',), name='unique_pagina_inicial_por_projeto'),
        ),
    ]
