# Generated by Django 5.2.17 on 2026-09-08 00:20

import aplicativos.sites.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_garantir_pagina_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoVisualProjeto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cor_primaria', models.CharField(default='#2563eb', help_text='Cor de destaque para botões principais e elementos ativos.', max_length=20, validators=[aplicativos.sites.models.validar_cor_hex], verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#38bdf8', help_text='Cor de apoio para detalhes, tags e acentos.', max_length=20, validators=[aplicativos.sites.models.validar_cor_hex], verbose_name='Cor Secundária')),
                ('cor_fundo', models.CharField(default='#ffffff', help_text='Cor de fundo da página do BioSite.', max_length=20, validators=[aplicativos.sites.models.validar_cor_hex], verbose_name='Cor de Fundo')),
                ('cor_superficie', models.CharField(default='#f8fafc', help_text='Cor de fundo para cards, containers e caixas.', max_length=20, validators=[aplicativos.sites.models.validar_cor_hex], verbose_name='Cor de Superfície')),
                ('cor_texto', models.CharField(default='#0f172a', help_text='Cor principal para títulos e textos corridos.', max_length=20, validators=[aplicativos.sites.models.validar_cor_hex], verbose_name='Cor do Texto')),
                ('cor_texto_secundario', models.CharField(default='#64748b', help_text='Cor para subtítulos, legendas e metadados.', max_length=20, validators=[aplicativos.sites.models.validar_cor_hex], verbose_name='Cor do Texto Secundário')),
                ('fonte_principal', models.CharField(choices=[('Inter, sans-serif', 'Inter (Moderna / Clean)'), ('Roboto, sans-serif', 'Roboto (Equilibrada)'), ('Poppins, sans-serif', 'Poppins (Geométrica / Tech)'), ('Montserrat, sans-serif', 'Montserrat (Marcante)'), ('Playfair Display, serif', 'Playfair Display (Elegante / Editorial)'), ('Plus Jakarta Sans, sans-serif', 'Plus Jakarta Sans (Moderna / Premium)'), ("-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Sistema (Nativa)')], default='Inter, sans-serif', max_length=100, verbose_name='Fonte Principal')),
                ('fonte_titulos', models.CharField(choices=[('Inter, sans-serif', 'Inter (Moderna / Clean)'), ('Roboto, sans-serif', 'Roboto (Equilibrada)'), ('Poppins, sans-serif', 'Poppins (Geométrica / Tech)'), ('Montserrat, sans-serif', 'Montserrat (Marcante)'), ('Playfair Display, serif', 'Playfair Display (Elegante / Editorial)'), ('Plus Jakarta Sans, sans-serif', 'Plus Jakarta Sans (Moderna / Premium)'), ("-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'Sistema (Nativa)')], default='Inter, sans-serif', max_length=100, verbose_name='Fonte de Títulos')),
                ('radius_padrao', models.CharField(default='12px', help_text='Ex: 0px, 8px, 12px, 20px, 9999px (pill).', max_length=20, verbose_name='Raio de Borda Padrão')),
                ('sombra_padrao', models.CharField(default='suave', help_text='nenhuma, suave, media, forte, glow.', max_length=20, verbose_name='Sombra Padrão')),
                ('largura_maxima_mobile', models.PositiveIntegerField(default=390, help_text='Largura de referência mobile (320px a 430px).', verbose_name='Largura Máxima Mobile')),
                ('configuracoes_extras', models.JSONField(blank=True, default=dict, verbose_name='Configurações Extras')),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_visual', to='sites.projetosite', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'configuração visual do projeto',
                'verbose_name_plural': 'configurações visuais dos projetos',
            },
        ),
        migrations.CreateModel(
            name='MidiaSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('arquivo', models.ImageField(upload_to='sites/midias/%Y/%m/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100, verbose_name='Tipo MIME')),
                ('tamanho_bytes', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('largura', models.PositiveIntegerField(default=0, verbose_name='Largura (px)')),
                ('altura', models.PositiveIntegerField(default=0, verbose_name='Altura (px)')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('AVATAR', 'Foto de Perfil / Avatar'), ('ICONE', 'Ícone'), ('LOGO', 'Logotipo')], default='IMAGEM', max_length=20, verbose_name='Tipo de Mídia')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='sites.projetosite', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'mídia do site',
                'verbose_name_plural': 'mídias do site',
                'ordering': ['-criado_em'],
            },
        ),
    ]
