# Generated by Django 5.2.17 on 2026-09-08 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_configuracaovisualprojeto_midiasite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoReutilizavel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Bloco')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('hero', 'Hero / Destaque'), ('perfil', 'Perfil / Bio'), ('links', 'Links / Botões'), ('servicos', 'Serviços / Produtos'), ('galeria', 'Galeria / Fotos'), ('contato', 'Contato / Conexão'), ('cta', 'Chamada para Ação'), ('localizacao', 'Localização / Mapa'), ('rodape', 'Rodapé'), ('outro', 'Outro')], db_index=True, default='hero', max_length=30, verbose_name='Categoria')),
                ('origem', models.CharField(choices=[('sistema', 'Sistema'), ('usuario', 'Meus Blocos')], db_index=True, default='sistema', max_length=20, verbose_name='Origem')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blocos/thumbnails/', verbose_name='Miniatura')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=10, verbose_name='Ordem')),
                ('estrutura_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot validado contendo a estrutura de uma seção com containers e elementos.', verbose_name='Snapshot Estrutural')),
            ],
            options={
                'verbose_name': 'bloco reutilizável',
                'verbose_name_plural': 'blocos reutilizáveis',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Modelo')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('biosite', 'BioSite'), ('cartao_digital', 'Cartão Digital NFC'), ('profissional', 'Profissional Liberal'), ('empresa', 'Empresa / Negócio'), ('comercio', 'Comércio / Varejo'), ('restaurante', 'Restaurante / Gastronomia'), ('portfolio', 'Portfólio / Criativo'), ('landing_page', 'Landing Page'), ('outro', 'Outro')], db_index=True, default='biosite', max_length=30, verbose_name='Categoria')),
                ('origem', models.CharField(choices=[('sistema', 'Sistema'), ('usuario', 'Meus Modelos')], db_index=True, default='sistema', max_length=20, verbose_name='Origem')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/', verbose_name='Miniatura')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=10, verbose_name='Ordem')),
                ('estrutura_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot validado contendo configuracao_visual e árvore de páginas.', verbose_name='Snapshot Estrutural')),
            ],
            options={
                'verbose_name': 'modelo de site',
                'verbose_name_plural': 'modelos de sites',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='projetosite',
            name='template_origem',
            field=models.ForeignKey(blank=True, help_text='Modelo/template utilizado como ponto de partida inicial (informativo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_derivados', to='sites.templatesite', verbose_name='Modelo de Origem'),
        ),
    ]
