# Generated by Django 5.2.17 on 2026-09-08 01:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_blocoreutilizavel_templatesite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projetosite',
            name='descricao_seo',
            field=models.CharField(blank=True, help_text='Meta description para mecanismos de busca e prévia no WhatsApp.', max_length=255, verbose_name='Descrição SEO'),
        ),
        migrations.AddField(
            model_name='projetosite',
            name='imagem_compartilhamento',
            field=models.ForeignKey(blank=True, help_text='Imagem exibida em links compartilhados no WhatsApp, Facebook, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_imagem_og', to='sites.midiasite', verbose_name='Imagem de Compartilhamento (OG)'),
        ),
        migrations.AddField(
            model_name='projetosite',
            name='indexavel',
            field=models.BooleanField(default=True, help_text='Permite indexação pelo Google e outros buscadores quando o site estiver publicado.', verbose_name='Indexável por Buscadores'),
        ),
        migrations.AddField(
            model_name='projetosite',
            name='titulo_seo',
            field=models.CharField(blank=True, help_text='Título para mecanismos de busca e redes sociais (deixe vazio para usar o nome do site).', max_length=160, verbose_name='Título SEO'),
        ),
        migrations.CreateModel(
            name='PublicacaoSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_versao', models.PositiveIntegerField(db_index=True, verbose_name='Número da Versão')),
                ('snapshot', models.JSONField(help_text='Snapshot estrutural canônico, validado e imutável do site publicado.', verbose_name='Snapshot Publicado')),
                ('schema_version', models.PositiveIntegerField(default=1, verbose_name='Versão do Schema')),
                ('hash_conteudo', models.CharField(db_index=True, help_text='Hash determinístico da representação canônica do conteúdo publicado.', max_length=64, verbose_name='Hash SHA-256 do Conteúdo')),
                ('publicado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Publicado em')),
                ('ativa', models.BooleanField(db_index=True, default=False, verbose_name='Publicação Ativa')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados Técnicos')),
                ('midias_referenciadas', models.ManyToManyField(blank=True, related_name='publicacoes_que_utilizam', to='sites.midiasite', verbose_name='Mídias Referenciadas')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='sites.projetosite', verbose_name='Projeto')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
            ],
            options={
                'verbose_name': 'publicação de site',
                'verbose_name_plural': 'publicações de sites',
                'ordering': ['-numero_versao'],
            },
        ),
        migrations.AddField(
            model_name='projetosite',
            name='publicacao_ativa',
            field=models.ForeignKey(blank=True, help_text='Ponteiro direto para a versão de publicação atualmente no ar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_ativo_set', to='sites.publicacaosite', verbose_name='Publicação Ativa'),
        ),
        migrations.AddConstraint(
            model_name='publicacaosite',
            constraint=models.UniqueConstraint(fields=('projeto', 'numero_versao'), name='unique_projeto_numero_versao'),
        ),
    ]
