# Generated by Django 5.2.17 on 2026-09-08 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_projetosite_descricao_seo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEnderecoSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('host', models.CharField(db_index=True, max_length=255, verbose_name='Host')),
                ('motivo', models.CharField(default='alteracao', help_text='Ex: alteracao_subdominio, remocao_dominio, arquivamento.', max_length=50, verbose_name='Motivo')),
                ('reservado_ate', models.DateTimeField(blank=True, help_text='Período de quarentena durante o qual o endereço não pode ser reivindicado por outro cliente.', null=True, verbose_name='Reservado Até')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_enderecos', to='sites.projetosite', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'histórico de endereço',
                'verbose_name_plural': 'histórico de endereços',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EnderecoSite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('host', models.CharField(db_index=True, help_text='Hostname normalizado e sem protocolo (ex: joao.seudominio.com ou www.joao.com.br).', max_length=255, unique=True, verbose_name='Host / Domínio Completo')),
                ('subdominio', models.CharField(blank=True, db_index=True, help_text="Identificador do subdomínio da plataforma (ex: 'joao').", max_length=63, null=True, verbose_name='Subdomínio')),
                ('tipo', models.CharField(choices=[('subdominio_plataforma', 'Subdomínio da Plataforma'), ('dominio_personalizado', 'Domínio Personalizado')], db_index=True, default='subdominio_plataforma', max_length=30, verbose_name='Tipo de Endereço')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Verificação'), ('verificado', 'Verificado / Pronto'), ('ativo', 'Ativo no Ar'), ('erro', 'Falha de Configuração DNS'), ('removido', 'Removido')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('principal', models.BooleanField(db_index=True, default=False, help_text='Endereço oficial para SEO canonical, compartilhamento, links e NFC.', verbose_name='Endereço Principal')),
                ('token_verificacao', models.CharField(blank=True, help_text='Token criptográfico para verificação de propriedade via registro TXT.', max_length=64, verbose_name='Token de Verificação DNS')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('ultima_checagem_em', models.DateTimeField(blank=True, null=True, verbose_name='Última Checagem em')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='sites.projetosite', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'endereço do site',
                'verbose_name_plural': 'endereços dos sites',
                'ordering': ['-principal', 'tipo', 'host'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('projeto',), name='unique_endereco_principal_por_projeto')],
            },
        ),
    ]
