# Generated by Django 5.2.17 on 2026-09-08 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_atribuir_subdominios_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInteligente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('token', models.CharField(db_index=True, help_text='Identificador opaco e imprevisível presente na URL gravada no chip ou QR Code.', max_length=32, unique=True, verbose_name='Token Público')),
                ('tipo', models.CharField(choices=[('nfc', 'Tag NFC'), ('qr', 'QR Code'), ('curto', 'Link Curto')], db_index=True, default='nfc', max_length=10, verbose_name='Tipo de Link')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], db_index=True, default='ativo', max_length=10, verbose_name='Status')),
                ('tipo_midia_fisica', models.CharField(blank=True, choices=[('cartao', 'Cartão PVC / Metal'), ('adesivo', 'Adesivo / Tag Resinada'), ('chaveiro', 'Chaveiro'), ('placa', 'Placa de Balcão / Acrílico'), ('outro', 'Outro')], default='cartao', max_length=30, verbose_name='Tipo de Mídia Física')),
                ('nome', models.CharField(help_text='Ex: Cartão Pessoal Dr. Carlos ou QR Placa Recepção.', max_length=120, verbose_name='Nome Administrativo')),
                ('descricao', models.TextField(blank=True, help_text='Informações internas como lote, destinatário ou data de entrega.', verbose_name='Descrição / Observações')),
                ('ativado_em', models.DateTimeField(blank=True, null=True, verbose_name='Ativado em')),
                ('desativado_em', models.DateTimeField(blank=True, null=True, verbose_name='Desativado em')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('projeto', models.ForeignKey(help_text='BioSite para o qual o visitante será redirecionado.', on_delete=django.db.models.deletion.PROTECT, related_name='links_inteligentes', to='sites.projetosite', verbose_name='Projeto BioSite')),
            ],
            options={
                'verbose_name': 'link inteligente',
                'verbose_name_plural': 'links inteligentes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoVinculoTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('motivo', models.CharField(blank=True, help_text='Ex: Reatribuição de cartão a novo cliente ou alteração de campanha.', max_length=255, verbose_name='Motivo')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado Por')),
                ('projeto_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sites.projetosite', verbose_name='Projeto Anterior')),
                ('projeto_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.projetosite', verbose_name='Novo Projeto')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_vinculos', to='sites.linkinteligente', verbose_name='Link Inteligente')),
            ],
            options={
                'verbose_name': 'histórico de vínculo da tag',
                'verbose_name_plural': 'histórico de vínculos de tags',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='linkinteligente',
            index=models.Index(fields=['token', 'status'], name='idx_link_token_status'),
        ),
        migrations.AddIndex(
            model_name='linkinteligente',
            index=models.Index(fields=['projeto', 'tipo'], name='idx_link_projeto_tipo'),
        ),
    ]
