# Generated by Django 5.2.17 on 2026-09-08 03:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_linkinteligente_historicovinculotag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAnalitico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('PAGE_VIEW', 'Visualização de Página'), ('SMARTLINK_NFC', 'Acesso via Link NFC'), ('SMARTLINK_QR', 'Acesso via QR Code'), ('COMPONENT_CLICK', 'Clique em Componente')], db_index=True, max_length=32, verbose_name='Tipo de Evento')),
                ('origem', models.CharField(choices=[('DIRETO_DESCONHECIDO', 'Direto / Não Identificado'), ('NFC', 'NFC'), ('QR', 'QR Code'), ('INTERNO', 'Navegação Interna')], db_index=True, default='DIRETO_DESCONHECIDO', max_length=32, verbose_name='Origem')),
                ('pagina_uuid', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Identificador da Página')),
                ('elemento_uuid', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Identificador do Elemento')),
                ('tipo_componente', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Tipo de Componente')),
                ('subitem_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Subitem / Rede / CTA')),
                ('ocorrido_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ocorrido em')),
                ('contexto_minimo', models.JSONField(blank=True, default=dict, verbose_name='Contexto Mínimo')),
                ('link_inteligente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analiticos', to='sites.linkinteligente', verbose_name='Link Inteligente')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_analiticos', to='sites.projetosite', verbose_name='Projeto')),
                ('publicacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analiticos', to='sites.publicacaosite', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'evento analítico',
                'verbose_name_plural': 'eventos analíticos',
                'ordering': ['-ocorrido_em'],
                'indexes': [models.Index(fields=['projeto', 'ocorrido_em'], name='idx_evt_proj_ocorrido'), models.Index(fields=['tipo_evento', 'ocorrido_em'], name='idx_evt_tipo_ocorrido'), models.Index(fields=['link_inteligente', 'ocorrido_em'], name='idx_evt_link_ocorrido'), models.Index(fields=['elemento_uuid', 'ocorrido_em'], name='idx_evt_elem_ocorrido'), models.Index(fields=['projeto', 'tipo_evento', 'ocorrido_em'], name='idx_evt_proj_tipo_data')],
            },
        ),
    ]
