# Generated by Django 5.2.17 on 2026-09-07 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID interno')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único global exposto em URLs e integrações externas.', unique=True, verbose_name='UUID público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Nome da pessoa física ou razão social.', max_length=150, verbose_name='Nome do Cliente')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome comercial da marca ou estabelecimento.', max_length=150, verbose_name='Nome Fantasia / Marca')),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato principal.', max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='Telefone fixo ou móvel.', max_length=30, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, help_text='Número de WhatsApp para contato rápido ou integração futura.', max_length=30, verbose_name='WhatsApp')),
                ('documento', models.CharField(blank=True, help_text='Documento fiscal (opcional).', max_length=30, verbose_name='CPF / CNPJ')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações administrativas sobre o cliente ou contrato.', verbose_name='Observações Internas')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('arquivado', 'Arquivado')], db_index=True, default='ativo', max_length=20, verbose_name='Status')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
    ]
